#!/usr/bin/env python3

import os
import sys
import re
import subprocess

if len(sys.argv) != 2:
    print("Invalid number of arguments")
    print("Please see android-manager help")
    sys.exit()

argument = sys.argv[1].lower()

if argument == "help":
    print("""
          Android Project Manager
          --------------------------
          This script will help you to manage your android
          application projects.  The commands that this script allows are:
            --help
            --install
            --create
            --build

          This script assumes that you are in your projects root directory when run. 

          help:  This command prints this current document.

          install:  Installs the project to your phone (not emulator).

          create:  Creates the project.  When creating the project it creates a folder
                   with the same name as your project.

          build:  Builds your project.""")
    print("\n")

elif argument == "install":
    #We need to compile a regular expression to find the apk
    #to be installed
    expression = re.compile("[A-Za-z]+-debug.apk")

    for directory in os.listdir("bin/"):
        apk = expression.match(directory)
        if apk is not None:
            break
    
    if apk is None:
        print("Please build project first")
    else:
        apk = "bin/" + apk.string
        subprocess.call(["adb","install", "-r", apk])

elif argument == "create":
    
    #Get list of android sdk versions installed 
    home = os.getenv("HOME")
    android_targets = os.listdir(home + "/.android/platforms/")
    android_targets = [android_targets[-2:] for android_targets in android_targets]
    android_targets.sort()

    project_name = input("Project Name: ")
    project_name = project_name.replace(" ", "")

    package_name = input("Package Name: ")
    package_name = package_name.replace(" ", "")

    print("\n")
    print("Select target sdk version")
    print("----------------------------")
    for version in android_targets:
        print("["+version+"]")

    target_version = ""
    while target_version not in android_targets:
        target_version = input("Target Version: ")

    target_version = "android-"+target_version

    os.mkdir(project_name)
    os.chdir(project_name)

    subprocess.call(["android", "create", "project", "--target", target_version,
                     "--name", project_name, "--path", ".", "--activity",
                     "MainActivity", "--package", package_name])

elif argument == "build":
    subprocess.call(["ant", "debug"])
else:
    print("Invalid argument")
    print("Please see android-manager help")

sys.exit()
