#!/usr/bin/env python3

import os
import sys
import re
import subprocess

if len(sys.argv) != 2:
    print("Invalid number of arguments")
    print("Please see android-manager help")
    sys.exit()

argument = sys.argv[1].lower()

if argument == "help":
    print("""
          Android Project Manager
          --------------------------
          This script will help you to manage your android
          application projects.  The commands that this script allows are:
            --help
            --install
            --create
            --build

          This script assumes that you are in your projects root directory when run. 

          help:  This command prints this current document.

          install:  Installs the project to your phone (not emulator).

          create:  Creates the project.  When creating the project it creates a folder
                   with the same name as your project.

          build:  Builds your project.""")

elif argument == "install":
    #We need to compile a regular expression to find the apk
    #to be installed
    expression = re.compile("[A-Za-z]+-debug.apk")

    for directory in os.listdir("bin/"):
        apk = expression.match(directory)
        if apk is not None:
            break
    
    if apk is None:
        print("Please build project first")
    else:
        apk = "bin/" + apk.string
        subprocess.call(["adb","install", "-r", apk])

elif argument == "create":
    sys.exit()
elif argument == "build":
    subprocess.call(["ant", "debug"])
else:
    print("Invalid argument")
    print("Please see android-manager help")

sys.exit()
